PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZFTS_RSCODEINFO CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.

PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZFTS_RSCODEINFO-CUSTNUM .
    FIELD ZFTS_RSCODEINFO-MVNTYPE .
    FIELD ZFTS_RSCODEINFO-SPLIND .
    FIELD ZFTS_RSCODEINFO-RSCODE .
    FIELD ZFTS_RSCODEINFO-DESCRIPTION .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZFTS_RSCODEINFO-CUSTNUM .
    FIELD ZFTS_RSCODEINFO-MVNTYPE .
    FIELD ZFTS_RSCODEINFO-SPLIND .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.

 MODULE CUSTOM_BUTTON.
